project:
  type: website

website:
  title: "AirBnBs in California"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: search.qmd
        text: Search 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



